program: train_imageslice.py
name: imageslice
method: random
metric:
  name: val_mse
  goal: minimize
parameters:
  learning_rate:
    values: [0.0001, 0.0003, 0.0006, 0.0009, 0.0012, 0.0015]
  batch_size:
    values: [128, 256, 512]
  min_lr_divisor:
    values: [1, 2, 3, 4, 5]
  dropout_p:
    values: [0.0, 0.1, 0.25, 0.5]